# Generated by Django 3.0 on 2019-12-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.CharField(max_length=100),
        ),
    ]
